#ifndef MOVELIST_H
#define MOVELIST_H

#include "Move.h"

map<string, Move*> MoveList = {
	/*{ "PLACEHOLDER", new Move("PLACEHOLDER") },
	{ "Pound", new Move("Pound") },
	{ "Karate Chop", new Move("Karate Chop") },
	{ "Double Slap", new Move("Double Slap") },
	{ "Comet Punch", new Move("Comet Punch") },
	{ "Mega Punch", new Move("Mega Punch") },
	{ "Pay Day", new Move("Pay Day") },
	{ "Fire Punch", new Move("Fire Punch") },
	{ "Ice Punch", new Move("Ice Punch") },
	{ "Thunder Punch", new Move("Thunder Punch") },
	{ "Scratch", new Move("Scratch") },
	{ "Vise Grip", new Move("Vise Grip") },
	{ "Guillotine", new Move("Guillotine") },
	{ "Razor Wind", new Move("Razor Wind") },
	{ "Swords Dance", new Move("Swords Dance") },
	{ "Cut", new Move("Cut") },
	{ "Gust", new Move("Gust") },
	{ "Wing Attack", new Move("Wing Attack") },
	{ "Whirlwind", new Move("Whirlwind") },
	{ "Fly", new Move("Fly") },
	{ "Bind", new Move("Bind") },
	{ "Slam", new Move("Slam") },
	{ "Vine Whip", new Move("Vine Whip") },
	{ "Stomp", new Move("Stomp") },
	{ "Double Kick", new Move("Double Kick") },
	{ "Mega Kick", new Move("Mega Kick") },
	{ "Jump Kick", new Move("Jump Kick") },
	{ "Rolling Kick", new Move("Rolling Kick") },
	{ "Sand Attack", new Move("Sand Attack") },
	{ "Headbutt", new Move("Headbutt") },
	{ "Horn Attack", new Move("Horn Attack") },
	{ "Fury Attack", new Move("Fury Attack") },
	{ "Horn Drill", new Move("Horn Drill") },
	{ "Tackle", new Move("Tackle") },
	{ "Body Slam", new Move("Body Slam") },
	{ "Wrap", new Move("Wrap") },
	{ "Take Down", new Move("Take Down") },
	{ "Thrash", new Move("Thrash") },
	{ "Double-Edge", new Move("Double-Edge") },
	{ "Tail Whip", new Move("Tail Whip") },
	{ "Poison Sting", new Move("Poison Sting") },
	{ "Twineedle", new Move("Twineedle") },
	{ "Pin Missile", new Move("Pin Missile") },
	{ "Leer", new Move("Leer") },
	{ "Bite", new Move("Bite") },
	{ "Growl", new Move("Growl") },
	{ "Roar", new Move("Roar") },
	{ "Sing", new Move("Sing") },
	{ "Supersonic", new Move("Supersonic") },
	{ "Sonic Boom", new Move("Sonic Boom") },
	{ "Disable", new Move("Disable") },
	{ "Acid", new Move("Acid") },
	{ "Ember", new Move("Ember") },
	{ "Flamethrower", new Move("Flamethrower") },
	{ "Mist", new Move("Mist") },
	{ "Water Gun", new Move("Water Gun") },
	{ "Hydro Pump", new Move("Hydro Pump") },
	{ "Surf", new Move("Surf") },
	{ "Ice Beam", new Move("Ice Beam") },
	{ "Blizzard", new Move("Blizzard") },
	{ "Psybeam", new Move("Psybeam") },
	{ "Bubble Beam", new Move("Bubble Beam") },
	{ "Aurora Beam", new Move("Aurora Beam") },
	{ "Hyper Beam", new Move("Hyper Beam") },
	{ "Peck", new Move("Peck") },
	{ "Drill Peck", new Move("Drill Peck") },
	{ "Submission", new Move("Submission") },
	{ "Low Kick", new Move("Low Kick") },
	{ "Counter", new Move("Counter") },
	{ "Seismic Toss", new Move("Seismic Toss") },
	{ "Strength", new Move("Strength") },
	{ "Absorb", new Move("Absorb") },
	{ "Mega Drain", new Move("Mega Drain") },
	{ "Leech Seed", new Move("Leech Seed") },
	{ "Growth", new Move("Growth") },
	{ "Razor Leaf", new Move("Razor Leaf") },
	{ "Solar Beam", new Move("Solar Beam") },
	{ "Poison Powder", new Move("Poison Powder") },
	{ "Stun Spore", new Move("Stun Spore") },
	{ "Sleep Powder", new Move("Sleep Powder") },
	{ "Petal Dance", new Move("Petal Dance") },
	{ "String Shot", new Move("String Shot") },
	{ "Dragon Rage", new Move("Dragon Rage") },
	{ "Fire Spin", new Move("Fire Spin") },
	{ "Thunder Shock", new Move("Thunder Shock") },
	{ "Thunderbolt", new Move("Thunderbolt") },
	{ "Thunder Wave", new Move("Thunder Wave") },
	{ "Thunder", new Move("Thunder") },
	{ "Rock Throw", new Move("Rock Throw") },
	{ "Earthquake", new Move("Earthquake") },
	{ "Fissure", new Move("Fissure") },
	{ "Dig", new Move("Dig") },
	{ "Toxic", new Move("Toxic") },
	{ "Confusion", new Move("Confusion") },
	{ "Psychic", new Move("Psychic") },
	{ "Hypnosis", new Move("Hypnosis") },
	{ "Meditate", new Move("Meditate") },
	{ "Agility", new Move("Agility") },
	{ "Quick Attack", new Move("Quick Attack") },
	{ "Rage", new Move("Rage") },
	{ "Teleport", new Move("Teleport") },
	{ "Night Shade", new Move("Night Shade") },
	{ "Mimic", new Move("Mimic") },
	{ "Screech", new Move("Screech") },
	{ "Double Team", new Move("Double Team") },
	{ "Recover", new Move("Recover") },
	{ "Harden", new Move("Harden") },
	{ "Minimize", new Move("Minimize") },
	{ "Smokescreen", new Move("Smokescreen") },
	{ "Confuse Ray", new Move("Confuse Ray") },
	{ "Withdraw", new Move("Withdraw") },
	{ "Defense Curl", new Move("Defense Curl") },
	{ "Barrier", new Move("Barrier") },
	{ "Light Screen", new Move("Light Screen") },
	{ "Haze", new Move("Haze") },
	{ "Reflect", new Move("Reflect") },
	{ "Focus Energy", new Move("Focus Energy") },
	{ "Bide", new Move("Bide") },
	{ "Metronome", new Move("Metronome") },
	{ "Mirror Move", new Move("Mirror Move") },
	{ "Self-Destruct", new Move("Self-Destruct") },
	{ "Egg Bomb", new Move("Egg Bomb") },
	{ "Lick", new Move("Lick") },
	{ "Smog", new Move("Smog") },
	{ "Sludge", new Move("Sludge") },
	{ "Bone Club", new Move("Bone Club") },
	{ "Fire Blast", new Move("Fire Blast") },
	{ "Waterfall", new Move("Waterfall") },
	{ "Clamp", new Move("Clamp") },
	{ "Swift", new Move("Swift") },
	{ "Skull Bash", new Move("Skull Bash") },
	{ "Spike Cannon", new Move("Spike Cannon") },
	{ "Constrict", new Move("Constrict") },
	{ "Amnesia", new Move("Amnesia") },
	{ "Kinesis", new Move("Kinesis") },
	{ "Soft-Boiled", new Move("Soft-Boiled") },
	{ "High Jump Kick", new Move("High Jump Kick") },
	{ "Glare", new Move("Glare") },
	{ "Dream Eater", new Move("Dream Eater") },
	{ "Poison Gas", new Move("Poison Gas") },
	{ "Barrage", new Move("Barrage") },
	{ "Leech Life", new Move("Leech Life") },
	{ "Lovely Kiss", new Move("Lovely Kiss") },
	{ "Sky Attack", new Move("Sky Attack") },
	{ "Transform", new Move("Transform") },
	{ "Bubble", new Move("Bubble") },
	{ "Dizzy Punch", new Move("Dizzy Punch") },
	{ "Spore", new Move("Spore") },
	{ "Flash", new Move("Flash") },
	{ "Psywave", new Move("Psywave") },
	{ "Splash", new Move("Splash") },
	{ "Acid Armor", new Move("Acid Armor") },
	{ "Crabhammer", new Move("Crabhammer") },
	{ "Explosion", new Move("Explosion") },
	{ "Fury Swipes", new Move("Fury Swipes") },
	{ "Bonemerang", new Move("Bonemerang") },
	{ "Rest", new Move("Rest") },
	{ "Rock Slide", new Move("Rock Slide") },
	{ "Hyper Fang", new Move("Hyper Fang") },
	{ "Sharpen", new Move("Sharpen") },
	{ "Conversion", new Move("Conversion") },
	{ "Tri Attack", new Move("Tri Attack") },
	{ "Super Fang", new Move("Super Fang") },
	{ "Slash", new Move("Slash") },
	{ "Substitute", new Move("Substitute") },
	{ "Struggle", new Move("Struggle") },
	{ "Sketch", new Move("Sketch") },
	{ "Triple Kick", new Move("Triple Kick") },
	{ "Thief", new Move("Thief") },
	{ "Spider Web", new Move("Spider Web") },
	{ "Mind Reader", new Move("Mind Reader") },
	{ "Nightmare", new Move("Nightmare") },
	{ "Flame Wheel", new Move("Flame Wheel") },
	{ "Snore", new Move("Snore") },
	{ "Curse", new Move("Curse") },
	{ "Flail", new Move("Flail") },
	{ "Conversion 2", new Move("Conversion 2") },
	{ "Aeroblast", new Move("Aeroblast") },
	{ "Cotton Spore", new Move("Cotton Spore") },
	{ "Reversal", new Move("Reversal") },
	{ "Spite", new Move("Spite") },
	{ "Powder Snow", new Move("Powder Snow") },
	{ "Protect", new Move("Protect") },
	{ "Mach Punch", new Move("Mach Punch") },
	{ "Scary Face", new Move("Scary Face") },
	{ "Feint Attack", new Move("Feint Attack") },
	{ "Sweet Kiss", new Move("Sweet Kiss") },
	{ "Belly Drum", new Move("Belly Drum") },
	{ "Sludge Bomb", new Move("Sludge Bomb") },
	{ "Mud-Slap", new Move("Mud-Slap") },
	{ "Octazooka", new Move("Octazooka") },
	{ "Spikes", new Move("Spikes") },
	{ "Zap Cannon", new Move("Zap Cannon") },
	{ "Foresight", new Move("Foresight") },
	{ "Destiny Bond", new Move("Destiny Bond") },
	{ "Perish Song", new Move("Perish Song") },
	{ "Icy Wind", new Move("Icy Wind") },
	{ "Detect", new Move("Detect") },
	{ "Bone Rush", new Move("Bone Rush") },
	{ "Lock-On", new Move("Lock-On") },
	{ "Outrage", new Move("Outrage") },
	{ "Sandstorm", new Move("Sandstorm") },
	{ "Giga Drain", new Move("Giga Drain") },
	{ "Endure", new Move("Endure") },
	{ "Charm", new Move("Charm") },
	{ "Rollout", new Move("Rollout") },
	{ "False Swipe", new Move("False Swipe") },
	{ "Swagger", new Move("Swagger") },
	{ "Milk Drink", new Move("Milk Drink") },
	{ "Spark", new Move("Spark") },
	{ "Fury Cutter", new Move("Fury Cutter") },
	{ "Steel Wing", new Move("Steel Wing") },
	{ "Mean Look", new Move("Mean Look") },
	{ "Attract", new Move("Attract") },
	{ "Sleep Talk", new Move("Sleep Talk") },
	{ "Heal Bell", new Move("Heal Bell") },
	{ "Return", new Move("Return") },
	{ "Present", new Move("Present") },
	{ "Frustration", new Move("Frustration") },
	{ "Safeguard", new Move("Safeguard") },
	{ "Pain Split", new Move("Pain Split") },
	{ "Sacred Fire", new Move("Sacred Fire") },
	{ "Magnitude", new Move("Magnitude") },
	{ "Dynamic Punch", new Move("Dynamic Punch") },
	{ "Megahorn", new Move("Megahorn") },
	{ "Dragon Breath", new Move("Dragon Breath") },
	{ "Baton Pass", new Move("Baton Pass") },
	{ "Encore", new Move("Encore") },
	{ "Pursuit", new Move("Pursuit") },
	{ "Rapid Spin", new Move("Rapid Spin") },
	{ "Sweet Scent", new Move("Sweet Scent") },
	{ "Iron Tail", new Move("Iron Tail") },
	{ "Metal Claw", new Move("Metal Claw") },
	{ "Vital Throw", new Move("Vital Throw") },
	{ "Morning Sun", new Move("Morning Sun") },
	{ "Synthesis", new Move("Synthesis") },
	{ "Moonlight", new Move("Moonlight") },
	{ "Hidden Power", new Move("Hidden Power") },
	{ "Cross Chop", new Move("Cross Chop") },
	{ "Twister", new Move("Twister") },
	{ "Rain Dance", new Move("Rain Dance") },
	{ "Sunny Day", new Move("Sunny Day") },
	{ "Crunch", new Move("Crunch") },
	{ "Mirror Coat", new Move("Mirror Coat") },
	{ "Psych Up", new Move("Psych Up") },
	{ "Extreme Speed", new Move("Extreme Speed") },
	{ "Ancient Power", new Move("Ancient Power") },
	{ "Shadow Ball", new Move("Shadow Ball") },
	{ "Future Sight", new Move("Future Sight") },
	{ "Rock Smash", new Move("Rock Smash") },
	{ "Whirlpool", new Move("Whirlpool") },
	{ "Beat Up", new Move("Beat Up") }*/
};



#endif
